# Generated by Django 4.0.6 on 2022-08-04 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0002_catagory_tb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='catagory_tb',
            new_name='category_tb',
        ),
        migrations.RenameField(
            model_name='category_tb',
            old_name='catagory_name',
            new_name='category_name',
        ),
    ]
